############################
## CHANGE THESE
############################

baseURL: "https://flowakening.github.io/qubtTemplate"
title: qubtTemplate

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
